### ISSUE TITLE
Ansible nodes role fails to generate SSL certificates

### ISSUE THREAD

**Issue by Rumbles** [scylladb/scylla-ansible-roles#10]
Hi as requested Guy Carmin, raising this as an issue. I'm doing a PoC of Scylla enterprise and I'm hitting an issue where I cannot deploy from the node playbook on to instances running Amazon Linux 2.

In my setup I use terraform to pull in dependencies, for example, I check out this repo from github as well as the one recommended for setting up swap, and I put them in the working directory. I also grab a CA Certificate from a local Vault and put that in an `ssl/ca` folder in working directory. 

I run the following command (via terraform):

`ansible-playbook -i inventory.ini nodes.yaml -e '@node-variables.yaml'`

In my working directory I have `nodes.yaml`:

```yaml
---
- name: Scylla node
  hosts: scylla
  become: true
  vars:

    #variables for the swap role
    swap_file_size_mb: '1024'

    scylla_dependencies:
      - curl
      - wget
    scylla_io_probe: True
    enable_mc_format: true
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'
    generate_monitoring_config: True

  roles:
    - ansible-role-swap
    - ansible-scylla-node
```

Then my `node-variables.yaml` (redacted my repo UUID):
```yaml
# URL of an RPM .repo file or a DEB .list file
scylla_repos:
  - http://repositories.scylladb.com/scylla/repo/UUID/centos/scylladb-2020.1.repo

# Options are oss|enterprise
scylla_edition: enterprise
scylla_version: latest

scylla_cluster_name: "devel-scylla-ee"

scylla_snitch: Ec2Snitch

# Manager Agent Backup configuration - this is a free text which will be inserted into the configuration file
# Please ensure it is a valid and working configuration. Please refer to the example configuration file and the
# documentation for detailed instructions
scylla_manager_agent_config: |
  s3:
    access_key_id: 12345678
    secret_access_key: QWerty123456789
    provider: AWS
    region: us-east-1c
    endpoint: https://foo.bar.baz
    server_side_encryption:
    sse_kms_key_id:
    upload_concurrency: 2
    chunk_size: 50M
    use_accelerate_endpoint: false

# Configure raid disks via scylla_setup. This requires a list of disks to add to the raid
scylla_raid_setup:
  - /dev/nvme1n1

scylla_seeds:
  - "10.72.7.6"

scylla_manager_enabled: true
scylla_manager_repo_url: "http://downloads.scylladb.com/rpm/centos/scylladb-manager-2.2.repo"
```

I appreciate that I haven't set my `scylla_manager_agent_config` variables yet, but I don't think that is causing my issue...

My `inventory.ini`:

```ini
[all]
ec2-user@10.72.7.6
ec2-user@10.72.7.37
ec2-user@10.72.7.82
ec2-user@10.72.7.107

[scylla]
ec2-user@10.72.7.6
ec2-user@10.72.7.37
ec2-user@10.72.7.82

[scylla-manager]
ec2-user@10.72.7.107

[scylla-monitoring]
ec2-user@10.72.7.107
```

In my working directory I have the following tree:

```
.                                                                                                                                                                                                                                                  [41/135936]
├── ansible-role-swap
│   ├── LICENSE
│   ├── README.md
│   ├── defaults
│   │   └── main.yml
│   ├── meta
│   │   └── main.yml
│   ├── molecule
│   │   └── default
│   │       ├── converge.yml
│   │       └── molecule.yml
│   └── tasks
│       ├── disable.yml
│       ├── enable.yml
│       └── main.yml
├── ansible-scylla-loader
│   ├── README.md
│   ├── defaults
│   │   └── main.yml
│   └── tasks
│       ├── Debian.yml
│       ├── RedHat.yml
│       └── main.yml
├── ansible-scylla-manager
│   ├── README.md
│   ├── defaults
│   │   └── main.yml
│   ├── files
│   │   └── perftune.py
│   ├── handlers
│   │   └── main.yml
│   ├── meta
│   │   └── main.yml
│   ├── tasks
│   │   ├── Debian.yml
│   │   ├── RedHat.yml
│   │   ├── add-clusters.yml
│   │   └── main.yml
│   ├── tests
│   │   ├── inventory
│   │   └── test.yml
│   └── vars
│       └── main.yml
├── ansible-scylla-monitoring
│   ├── README.md
│   ├── defaults
│   │   └── main.yml
│   ├── handlers
│   │   └── main.yml
│   ├── meta
│   │   └── main.yml
│   ├── tasks
│   │   ├── Debian.yml
│   │   ├── RedHat.yml
│   │   ├── common.yml
│   │   ├── docker.yml
│   │   ├── main.yml
│   │   └── non-docker.yml
│   ├── tests
│   │   ├── inventory
│   │   └── test.yml
│   └── vars
│       └── main.yml
├── ansible-scylla-node
│   ├── README.md
│   ├── defaults
│   │   └── main.yml
│   ├── files
│   │   └── minigenconfig.py
│   ├── handlers
│   │   └── main.yml
│   ├── meta
│   │   └── main.yml
│   ├── tasks
│   │   ├── Debian.yml
│   │   ├── RedHat.yml
│   │   ├── common.yml
│   │   ├── main.yml
│   │   ├── manager_agents.yml
│   │   ├── monitoring_config.yml
│   │   └── ssl.yml
│   ├── templates
│   │   ├── cassandra-rackdc.properties.j2
│   │   ├── cqlshrc.j2
│   │   ├── io_properties.yaml.j2
│   │   ├── scylla-manager-agent.yaml.j2
│   │   └── scylla.yaml.j2
│   ├── tests
│   │   ├── inventory
│   │   └── test.yml
│   └── vars
│       └── main.yml
├── inventory.ini
├── manager-variables.yaml
├── manager.yaml
├── monitoring.yaml
├── node-variables.yaml
├── nodes.yaml
└── ssl
    └── ca
        └── devel-scylla-ee-ca.pem

35 directories, 66 files
```

I'm in your Slack if you need to get in touch (James Stocker)

Thanks!

Most of the ansible play seems to work fine, but when I get to the SSL steps toward the end I get this error:

```
null_resource.execute_ansible_playbook_nodes (local-exec): TASK [ansible-scylla-node : enable ssl options] ********************************
null_resource.execute_ansible_playbook_nodes (local-exec): included: /Users/stocker/git/infrastructure/resources/scylla/build/assets/ansible/ansible-scylla-node/tasks/ssl.yml for ec2-user@10.72.7.6, ec2-user@10.72.7.37, ec2-user@10.72.7.82

null_resource.execute_ansible_playbook_nodes (local-exec): TASK [ansible-scylla-node : Create dir for the CA] *****************************
null_resource.execute_ansible_playbook_nodes (local-exec): fatal: [ec2-user@10.72.7.6]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1}
```

I haven't set up passwords on the target host (It has just been deployed and then this playbook ran on it - I am able to ssh on to the machine and sudo as ec2-user without it asking me for a password at the same time this error occurs)
