### ISSUE TITLE
audit _categories don't get writtten for scylla.yaml

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#120]
If you use 

```
scylla_yaml_params:
  authenticator: PasswordAuthenticator
  authorizer: CassandraAuthorizer
  audit: "table"
  audit_categories: "DCL,DDL,AUTH,ADMIN"
  audit_keyspaces: "ads_moj_monetization"  
```

it won't write the line `audit_categories: "DCL,DDL,AUTH,ADMIN"` to the file
if you rearrange:
```
scylla_yaml_params:
  authenticator: PasswordAuthenticator
  authorizer: CassandraAuthorizer
  audit: "table"  
  audit_keyspaces: "ads_moj_monetization"  
  audit_categories: "DCL,DDL,AUTH,ADMIN"
```

they will
