### ISSUE TITLE
[Scylla Node Role]: update node_exporter service name

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-ansible-roles#136]
Node exporter bundled with Scylla has its name changed from `node-exporter` to `scylla-node-exporter`. Thus, all affected builds are failing to start node-exporter during deployment with the Ansible Node role as it currently handles the old name only:
https://github.com/scylladb/scylla-ansible-roles/blob/75a55ddacb338e5ec17349f536812568d4f990e4/ansible-scylla-node/handlers/main.yml#L27-L32

Changed on:
https://github.com/scylladb/scylla/commit/95197a09c91eb719c252abed847b8c035f5f9600

Affects: scylla-4.4.0+, scylla-enterprise-2022.1~rc0+

**Comment by fee-mendes** [comment]
Best is to start both and ignore any errors. Supporting one or another is just a way to see it being left down in the long run. E.g:

```yaml
  post_tasks:
    - name: "Enable and start node exporter"
      systemd:
        name: scylla-node-exporter
        enabled: True
        state: started
      ignore_errors: true
```

Although IMHO, this should've been a scylla-server After dependency, just like `scylla-jmx` is (for consistency and our own sanity), eg:

```shell
Requires=scylla-server.service
After=scylla-server.service
```

@vladzcloudius WDYT? I vote for an issue on the OSS list as well. :-)
