### ISSUE TITLE
compatibility with ubuntu 22.04

### ISSUE THREAD

**Issue by sorushsaghari** [scylladb/scylla-ansible-roles#279]
i need to install scylladdb on ubuntu-22.04. 
A change is needed for apt gpg key like this:
```yaml
 tasks:
    - name: Download GPGs
      ansible.builtin.shell: |
        set -e
        sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/scylladb.gpg --keyserver hkp://[keyserver.ubuntu.com:80](http://keyserver.ubuntu.com/) --recv-keys d0a112e067426ab2
      changed_when: true
```
since apt-key is deprecated. 
is this in your plan to add it? or can i add it and make pull requests?
