### ISSUE TITLE
[Node/Loader Roles]: Get rid of explicit arch mentioning of 'amd' arch in the code

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ansible-roles#325]
HEAD: ff58a6035d03225ff9002714bc0a522372c38de9

*Description*
Two invocations of `alternatives` module refer an `amd` arch explicitly:

```
- name: Correct java version selected
    alternatives:
      name: java
      path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

This makes this code not portable.
