### ISSUE TITLE
[ansible-scylla-node] Running the role fails when an existing APT key was updated

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-ansible-roles#329]
### Issue
If the role is executed in a node when the APT key used by Scylla was updated (because it expired but keeping its ID), APT won't update it locally leading to an error when it tries to re-synchronize the package index files from their sources.

### Reproducer
Running the role without on a node where the expired key is present and where an updated key with the same ID is available.

Message shown by Ansible:
```
fatal: [...]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: unknown reason"}
```

Message shown when `sudo apt-get update` is manually executed:
```
Err:8 http://downloads.scylladb.com/downloads/scylla-enterprise/deb/debian-ubuntu/scylladb-2022.2 stable InRelease
  The following signatures were invalid: EXPKEYSIG D0A112E067426AB2 ScyllaDB Package Signing Key 2022 <security@scylladb.com>
```

Those two errors proves if the key is present, it won't be updated by Ansible.

Ref:
- https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#notes

**Comment by tarzanek** [comment]
Scylla did re-sing the key D0A112E067426AB2 
so all old installations need to refresh the keys, which is easier said than done

this worked for me:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D0A112E067426AB2

sudo mkdir -p /etc/apt/keyrings
sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/scylladb.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys d0a112e067426ab2

sudo pkill dirmngr

sudo pkill gpg-agent
```
but it assumes enterprise repo file, the repo file path to keyring has to correspond to above

**Comment by tarzanek** [comment]
so role should do on top of what it does now:
1) make sure the key is properly refreshed even after it expires
2) make sure we properly place the key into proper path from repo file

**Comment by ebenzecri** [comment]
This part of the code is making the role fail when the key is already expired:
```
  - name: Install gnupg2 dependency
    apt:
      name: "gnupg2"
      state: present
      update_cache: yes
    when: install_type == 'online' and scylla_repo_keyserver is defined and scylla_repo_keys is defined and (scylla_repo_keys|length > 0)
```

`update_cache: yes` must be removed. It's also not required to just simple install `gnupg2`.
