### ISSUE TITLE
Use ansible.builtin.password plugin instead of shell

### ISSUE THREAD

**Issue by elcomtik** [scylladb/scylla-ansible-roles#56]
You should use the [password](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_lookup.html) plugin to generate a password instead of executing the shell command and copying it to localhost. It can be handled in one task instead of the current two.

https://github.com/scylladb/scylla-ansible-roles/blob/da4a7ae1b3bfce4408211271582227d25500429c/ansible-scylla-node/tasks/manager_agents.yml#L10-L26

**Comment by elcomtik** [comment]
Actually, it can replace the following task also.
https://github.com/scylladb/scylla-ansible-roles/blob/da4a7ae1b3bfce4408211271582227d25500429c/ansible-scylla-node/tasks/manager_agents.yml#L28-L39

**Comment by elcomtik** [comment]
All of this can be replaced by this code
```
- name: Get token from file or generate a new token and store on controller
  set_fact:
    auth_token: "{{ lookup('password', 'scyllamgr_auth_token.txt chars=ascii_lowercase,ascii_uppercase,digits length=128') }}"
  run_once: true
```
