### ISSUE TITLE
monitoring: provide option to enable auth-ed cql monitoring of large *

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#93]
add to `grafana/datasource.yml`

```
- name: scylla-datasource
  type: scylladb-scylla-datasource
  orgId: 1
  isDefault:
  jsonData:
    host: 'node-ip'
  secureJsonData:
    user: 'cassandra'
    password: 'cassandra'
```

to enable large partition/cell/rows monitoring from monitor when behind cql auth
(without auth it should work out of box per https://github.com/scylladb/scylla-monitoring/tree/branch-3.7/grafana/plugins/scylla-plugin )
